Refactoring to reuse enviroments
- Avoid bugsinpy-compile whenever possible
- Saves index with all the results
- COntinues previous index

diff --git a/framework/bin/bugsinpy-testall b/framework/bin/bugsinpy-testall
--- a/framework/bin/bugsinpy-testall
+++ b/framework/bin/bugsinpy-testall
@@ -3,20 +3,18 @@
 
 ###bugsinpy-testall reproduces all the bugs for every project
 # test ok (reproduced successfully) test fail (unable to reproduce)
-# Full setup logs in each $DIR/projects/$project/logs.txt
-# output.csv in $OUTPUT
-# Filex bug_fixed.txt and bug_buggy.txt are added to each project bug
+# Files bug_fixed.txt and bug_buggy.txt are added to each project bug
+# Index result in BugsInPy/projects/index.csv
+# Full setup logs in temp/$project/logs.txt 
 
 DIR="/home/user"
-OUTPUT="$DIR/projects/output.csv"
-# DIR_OF_SCRIPT=$(dirname $0)
-# DIR_OF_PROJECT=$(realpath $(dirname $0)/../..)
+INDEX="$DIR/BugsInPy/projects/index.csv"
 
 usage="
        -h
              show this help
        -c
-             cleanup $DIR directory
+             cleanup temp directory
        -p
              specify multiple project:start:end or project:end or project:
              Ex;
@@ -30,11 +28,8 @@ case $1 in
     echo "$usage"
     exit 0;;
  -c)
-    read -p "Are you sure? [y/n]" -n 1 -r
-    if [[ $REPLY =~ ^[Yy]$ ]]
-    then
-      rm -rfv "$DIR/projects/*"
-    fi
+    rm -rf $DIR/projects/*
+    touch .gitkeep
     exit 0;;
  -p)
     projects="${@:2}";;
@@ -46,16 +41,10 @@ if ! echo $projects | grep -q ":"; then
   projects=$(ls $DIR/BugsInPy/projects)
 fi
 
-echo "Reproducing bugs please wait ..."
-echo "---------------"
-
-touch $OUTPUT
-if ! grep "repo,bugid,version,result" $OUTPUT; then
-  echo "repo,bugid,version,result" | tee $OUTPUT
+if [ ! -f $INDEX ]; then
+  echo "repo,bugid,version,result" > $INDEX
 fi
 
-# Cleanup unfinished reproductions
-sed -i '/[0-9]$/d' $OUTPUT
 # Iterate over the projects
 for project in $projects; do
 
@@ -79,64 +68,87 @@ for project in $projects; do
   for bug in $(seq $start $finish); do
 
     BUG_SOURCE_DIR="$DIR/BugsInPy/projects/$project/bugs/$bug"
-
-    if [ -d "$BUG_SOURCE_DIR" ]; then
-      # echo $LINENO # debug
-
+    if ! grep "$project,$bug," $INDEX && [ -d "$BUG_SOURCE_DIR" ]; then
+      touch $BUG_SOURCE_DIR/requirements.txt
       work_dir="$DIR/projects/$project"
-      mkdir -p $work_dir
-      cd $work_dir
+      projects_dir="$DIR/projects"
+      BUG_INFO="$work_dir/bugsinpy_bug.info"
 
       # Test buggy (0) version
-      bugsinpy-checkout -p $project -v 0 -i $bug -w $DIR/projects &>> $work_dir/logs.txt
+      bugsinpy-checkout -p $project -v 0 -i $bug -w $projects_dir &>> /dev/null
 
+      cd $work_dir
 
       ###Required to use conda activate, included in docker continuumio/miniconda3
       . /opt/conda/etc/profile.d/conda.sh &>> $work_dir/logs.txt
       ###Setup proper python version already installed using miniconda
-      bug_python_version=$(grep -o "3\..\.." bugsinpy_bug.info)
+      bug_python_version=$(grep -o "3\..\.." $BUG_INFO)
 
       ###Add environment
-      dos2unix $work_dir/bugsinpy_requirements.txt
+      REQUIREMENTS="$work_dir/bugsinpy_requirements.txt"
+      dos2unix $REQUIREMENTS &>/dev/null
       . /opt/conda/etc/profile.d/conda.sh
-      bug_python_version=$(grep -o "3\..\.." "$work_dir/bugsinpy_bug.info")
-      conda_env_name=$(cat <(echo $bug_python_version) "$work_dir/bugsinpy_requirements.txt" | md5sum | cut -d' ' -f 1)
-      if ! conda env list | grep -q "$conda_env_name"; then
-        conda create -n $conda_env_name -y python=$bug_python_version &>> $work_dir/logs.txt
+      sed -i -e '/^\s*#.*$/d' -e '/^\s*$/d' "$REQUIREMENTS"
+      bug_python_version=$(grep -o "3\..\.." "$BUG_INFO")
+      conda_env_name=$(cat <(echo $bug_python_version) "$REQUIREMENTS" | md5sum | cut -d' ' -f 1)
+      if conda env list | grep -q "$conda_env_name"; then
+        touch "$work_dir/bugsinpy_compile_flag"
+      else
+        conda create -n $conda_env_name -y python=$bug_python_version pytest &>> $work_dir/logs.txt
+        bugsinpy-compile &>> $work_dir/logs.txt
       fi
 
-      # TODO: Develop custom fixes for failing libraries
-      # if echo $work_dir | grep -q xyz; then
-      #   conda install -y -c conda-forge xyz=2.2.5
-      # fi
-
-      bugsinpy-compile &>> $work_dir/logs.txt
       bugsinpy-test &> $BUG_SOURCE_DIR/bug_buggy.txt
 
       # Make sure a failure is detected in buggy version and bug is reproducible
-      if grep -q "= ERRORS =" $BUG_SOURCE_DIR/bug_buggy.txt || grep -q ": command not found" $BUG_SOURCE_DIR/bug_buggy.txt ;then
-        echo "$project,$bug,buggy,error" | tee -a $OUTPUT
-      elif [ -f "bugsinpy_fail.txt" ]; then
-        echo "$project,$bug,buggy,fail" | tee -a $OUTPUT
+      if grep -q "= FAILURES =" $BUG_SOURCE_DIR/bug_buggy.txt || \
+         grep -q "FAILED (" $BUG_SOURCE_DIR/bug_buggy.txt
+      then
+        echo "$project,$bug,buggy,fail" | tee -a $INDEX
+      elif grep -q "= ERRORS =" $BUG_SOURCE_DIR/bug_buggy.txt || \
+         grep -q ": command not found" $BUG_SOURCE_DIR/bug_buggy.txt || \
+         grep -q "You have not compile this project" $BUG_SOURCE_DIR/bug_buggy.txt
+      then
+        echo "$project,$bug,buggy,error" | tee -a $INDEX
+      elif grep -qwE "passed|OK" $BUG_SOURCE_DIR/bug_buggy.txt; then
+        echo "$project,$bug,buggy,pass" | tee -a $INDEX
       else
-        echo "$project,$bug,buggy,pass" | tee -a $OUTPUT
+        echo "$project,$bug,buggy,unknown" | tee -a $INDEX
       fi
+
+      # echo $LINENO # debug
 
       # Test fixed (1) version
       bugsinpy-checkout -p $project -v 1 -i $bug -w $DIR/projects &>> $work_dir/logs.txt
-      bugsinpy-compile &>> $work_dir/logs.txt
+
+      ### Check for same enviroment and avoid recompiling
+      dos2unix $REQUIREMENTS &>/dev/null
+      sed -i -e '/^\s*#.*$/d' -e '/^\s*$/d' "$REQUIREMENTS"
+      bug_python_version=$(grep -o "3\..\.." "$BUG_INFO")
+      conda_env_name=$(cat <(echo $bug_python_version) "$REQUIREMENTS" | md5sum | cut -d' ' -f 1)
+      if conda env list | grep -q "$conda_env_name"; then
+        touch "$work_dir/bugsinpy_compile_flag"
+      else
+        conda create -n $conda_env_name -y python=$bug_python_version pytest &>> $work_dir/logs.txt
+        bugsinpy-compile &>> $work_dir/logs.txt
+      fi
       bugsinpy-test &> $BUG_SOURCE_DIR/bug_fixed.txt
 
       # Test execution output and make sure fixed version passes test ok
-      if grep -q "= ERRORS =" $BUG_SOURCE_DIR/bug_fixed.txt || grep -q ": command not found" $BUG_SOURCE_DIR/bug_fixed.txt ;then
-        echo "$project,$bug,fixed,error" | tee -a $OUTPUT
-      elif [ -f "bugsinpy_fail.txt" ]; then
-        echo "$project,$bug,fixed,fail" | tee -a $OUTPUT
+      if grep -q "= FAILURES =" $BUG_SOURCE_DIR/bug_fixed.txt || \
+         grep -q "FAILED (" $BUG_SOURCE_DIR/bug_fixed.txt
+      then
+        echo "$project,$bug,fixed,fail" | tee -a $INDEX
+      elif grep -q "= ERRORS =" $BUG_SOURCE_DIR/bug_fixed.txt || \
+         grep -q ": command not found" $BUG_SOURCE_DIR/bug_fixed.txt || \
+         grep -q "You have not compile this project" $BUG_SOURCE_DIR/bug_fixed.txt
+      then
+        echo "$project,$bug,fixed,error" | tee -a $INDEX
+      elif grep -qwE "passed|OK" $BUG_SOURCE_DIR/bug_fixed.txt; then
+        echo "$project,$bug,fixed,pass" | tee -a $INDEX
       else
-        echo "$project,$bug,fixed,pass" | tee -a $OUTPUT
+        echo "$project,$bug,fixed,unknown" | tee -a $INDEX
       fi
     fi
   done
 done
-
-echo "done."
